// Code generated by ent, DO NOT EDIT.

package delivery

const (
	// Label holds the string label denoting the delivery type in the database.
	Label = "delivery"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeliveredQuantity holds the string denoting the delivered_quantity field in the database.
	FieldDeliveredQuantity = "delivered_quantity"
	// EdgeOrderItem holds the string denoting the order_item edge name in mutations.
	EdgeOrderItem = "order_item"
	// Table holds the table name of the delivery in the database.
	Table = "deliveries"
	// OrderItemTable is the table that holds the order_item relation/edge.
	OrderItemTable = "deliveries"
	// OrderItemInverseTable is the table name for the OrderItem entity.
	// It exists in this package in order to avoid circular dependency with the "orderitem" package.
	OrderItemInverseTable = "order_items"
	// OrderItemColumn is the table column denoting the order_item relation/edge.
	OrderItemColumn = "order_item_deliveries"
)

// Columns holds all SQL columns for delivery fields.
var Columns = []string{
	FieldID,
	FieldDeliveredQuantity,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "deliveries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"order_item_deliveries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
